// /*
//  * This source file was generated by the Gradle 'init' task
//  */
// package org.example;

// import java.util.ArrayList;
// import java.util.List;

// import org.example.controllers.ChannelController;
// import org.example.models.Channel;
// import org.example.models.User;
// import org.example.views.MainFrame;

// public class App {
//     public String getGreeting() {
//         return "Hello World!";
//     }

//     public static void main(String[] args) {
//          // Sample users
//         List<User> users = new ArrayList<>();
//         users.add(new User("Alice"));
//         users.add(new User("Bob"));

//         // Sample channels
//         List<Channel> channels = new ArrayList<>();
//         channels.add(new Channel(new ArrayList<>(), new ArrayList<>(), "Tech News"));
//         channels.add(new Channel(new ArrayList<>(), new ArrayList<>(), "Sports Updates"));

//         // Channel controllers
//         List<ChannelController> controllers = new ArrayList<>();
//         for (Channel channel : channels) {
//             controllers.add(new ChannelController(channel));
//         }

//         // Launch MainFrame
//         new MainFrame(controllers, users);
//     }
// }
