/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.views.SocialMediaAppSwing;

public class App {
   
    public static void main(String[] args) {
       
        new SocialMediaAppSwing();

    }
}
